services:
  - type: web
    name: portfolyo
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: USE_SQLSERVER
        value: "false"
      - key: MIGRATE_LOCAL_TO_POSTGRES
        value: "false"
      - key: ADMIN_KEY
        sync: false
      - key: JWT_ISSUER
        value: portfolyo
      - key: JWT_AUDIENCE
        value: portfolyo-admin
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_MINUTES
        value: "120"
      - key: DATABASE_URL
        sync: false
